service: sg-hazy-bot
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-1
# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
 patterns:
   - '!.github/**'
   - '!terraform/**'
   - ./*.py

functions:
  main:
    handler: lambda_function.lambda_handler
    name: lambda-sg-hazy-bot