name: deploy-aws-lambda
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        node-version: [14.x]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          python -m unittest tests/*.py
      - name: Deploy code to Lambda
        uses: kohrongying/py-lambda-action@master
        with:
          lambda_layer_arn: 'arn:aws:lambda:ap-southeast-1:163368111864:layer:lambda-layer-python38-requests'
          lambda_function_name: 'lambda-sg-hazy-bot'
          exclude_files: 'tests .github terraform serverless.yml'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-1'